# Generated by Django 5.2.10 on 2026-01-07 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=10)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='bronze', max_length=20)),
                ('xp_reward', models.IntegerField(default=50)),
                ('condition_type', models.CharField(max_length=50)),
                ('condition_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🎯', max_length=10)),
                ('challenge_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20)),
                ('category', models.CharField(choices=[('no_spend', 'No Spend'), ('budget', 'Stay Under Budget'), ('track', 'Track Expenses'), ('save', 'Save Money')], max_length=50)),
                ('target_value', models.IntegerField(default=0)),
                ('excluded_categories', models.JSONField(default=list)),
                ('xp_reward', models.IntegerField(default=25)),
                ('streak_bonus', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_expense_date', models.DateField(blank=True, null=True)),
                ('streak_multiplier', models.FloatField(default=1.0)),
                ('theme', models.CharField(choices=[('dark', 'Dark Mode'), ('light', 'Light Mode'), ('neon', 'Neon Glow'), ('midnight', 'Midnight Blue'), ('forest', 'Forest Green')], default='dark', max_length=20)),
                ('unlocked_themes', models.JSONField(default=list)),
                ('unlocked_insights', models.JSONField(default=list)),
                ('total_saved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('challenges_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.challenge')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='tracker.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'challenge', 'started_at')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.achievement')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='tracker.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('alltime', 'All Time')], max_length=20)),
                ('period_start', models.DateField()),
                ('xp_earned', models.IntegerField(default=0)),
                ('challenges_completed', models.IntegerField(default=0)),
                ('achievements_earned', models.IntegerField(default=0)),
                ('savings_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rank', models.IntegerField(default=0)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.userprofile')),
            ],
            options={
                'ordering': ['-xp_earned'],
                'unique_together': {('user_profile', 'period_type', 'period_start')},
            },
        ),
    ]
